trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
# Check formatting
- template: ci/rustfmt.yml
  parameters:
    name: rustfmt
    displayName: Check formatting

# Cargo check
- template: ci/cargo-check.yml
  parameters:
    name: cargo_check
    displayName: Cargo check

# This represents the minimum Rust version supported.
# Tests are not run as tests may require newer versions of rust.
- template: ci/cargo-check.yml
  parameters:
    name: minrust
    rust_version: 1.37.0
    displayName: Check rust min ver

################
# Test stage   #
###############

# Test stable
- template: ci/test.yml
  parameters:
    dependsOn:
      - cargo_check
    name: cargo_test_stable
    displayName: Cargo test
    cross: true # Test on Windows and macOS

# Test nightly
- template: ci/test.yml
  parameters:
    name: cargo_test_nightly
    displayName: Cargo test
    rust_version: nightly
