jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}
      components:
              - clippy

  - script: cargo clippy --all 
    displayName: Run clippy
